{
 "title": "Microservice Health Status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Health Status Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "MicroService Status",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "probe_success" }
     ]
    }
   ]
  },
  {
   "title": "Application Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Ingestion Gauge",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "total_source" }
     ]
    },
    {
     "title": "Ingestion Gauge",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "sftp_source" },
      { "expr": "email_source" },
      { "expr": "kafka_source" },
      { "expr": "mq_source" },
      { "expr": "ndm_source" }
     ]
    },
    {
     "title": "Transformation Counter",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "transformation_total" }
     ]
    }
   ]
  }
 ]
}