scrape_configs:
  - job_name: 'ingestion-service'
    scrape_interval: 4s
    #scrape_timeout: 7s
    metrics_path: '/actuator/prometheus'
    # spring boot url
    static_configs:
      - targets: ['192.168.3.10:8082']
  - job_name: 'transformation-service'
    scrape_interval: 4s
    #scrape_timeout: 10s
    metrics_path: '/actuator/prometheus'
    # spring boot url
    static_configs:
      - targets: ['192.168.3.10:8081']
  - job_name: 'blackbox'
    scrape_interval: 4s
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets: ['192.168.3.10:8081']
        labels:
          name: 'transformation-service'
      - targets: ['192.168.3.10:8082']
        labels:
          name: 'ingestion-service'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.159.147:9115  # The blackbox exporter's real hostname:port.
